/**
 * A prepared OIDC authorization request. The PKCE challenge, `state`, and
 * `nonce` are generated by the OIDC provider; the flow's only job is to transport
 * the user to the authorization endpoint and capture the resulting code.
 */
export interface AuthorizationRequest {
  authorizationEndpoint: string;
  clientId: string;
  /** Redirect URI registered for the flow (a dynamic loopback URI on desktop). */
  redirectUri: string;
  scopes: readonly string[];
  /** PKCE S256 code challenge. */
  codeChallenge: string;
  /** Opaque CSRF token; must be echoed back unchanged in the response. */
  state: string;
  /** Replay-protection nonce, bound into the issued ID token. */
  nonce: string;
}

/** The result of an authorization redirect. */
export interface AuthorizationResponse {
  code: string;
  /** State returned by the authorization server; the caller MUST verify it matches. */
  state: string;
  /** The redirect URI actually used (the loopback port is dynamic on desktop). */
  redirectUri: string;
}

/**
 * The platform seam that performs the authorization redirect and captures the
 * code. Keeping this separate from the OIDC protocol logic lets desktop and web
 * share the protocol code and lets tests run without any browser or network.
 *
 * Implementations:
 * - {@link FakeAuthorizationFlow} — tests (this package).
 * - `LoopbackAuthorizationFlow` — Tauri desktop, system browser + loopback
 *   listener per RFC 8252 (follow-up).
 * - `RedirectAuthorizationFlow` — web/PWA full-page or popup redirect (follow-up).
 */
export interface AuthorizationFlow {
  authorize(request: AuthorizationRequest): Promise<AuthorizationResponse>;
}

export interface FakeAuthorizationFlowOptions {
  /** Authorization code to return. */
  code?: string;
  /** State to return; defaults to echoing the request state. Override to simulate a mismatch. */
  returnedState?: string;
  /** When set, `authorize` rejects with this error (e.g. user cancellation). */
  error?: Error;
}

/**
 * Test {@link AuthorizationFlow} that returns a canned authorization code and
 * records the requests it received, without any browser or network I/O.
 */
export class FakeAuthorizationFlow implements AuthorizationFlow {
  readonly requests: AuthorizationRequest[] = [];
  readonly #options: FakeAuthorizationFlowOptions;

  constructor(options: FakeAuthorizationFlowOptions = {}) {
    this.#options = options;
  }

  async authorize(request: AuthorizationRequest): Promise<AuthorizationResponse> {
    this.requests.push(request);
    if (this.#options.error) {
      throw this.#options.error;
    }
    return {
      code: this.#options.code ?? "fake-auth-code",
      state: this.#options.returnedState ?? request.state,
      redirectUri: request.redirectUri,
    };
  }
}
